version: "3.5"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/django
      - .mysite.conf:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn mysite.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/django/
    ports:
      - "8000:8000"
    expose:
      - "8000"
