version: "3.5"
services:
  nginx:
    container_name: nginx_service
    image: nginx:latest
    volumes:
      - .mysite.conf:/etc/nginx/conf.d
      - .:/django
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn mysite.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/django/
    ports:
      - "8000:8000"
    expose:
      - "8000"
